### ISSUE TITLE
DataConverting: Acolumn-vector y was paased when a 1 1d array was expected. Please change the shape of y to (n_sample)

### ISSUE THREAD

**Issue by ScarletBlaze** [IIIS-Li-Group/OpenFE#2]
Thanks for sharing, but I'm having a problem. It is that even if my label y is a 1-d vector, it still reports the following warning. What is the reason for this?
![QQ图片20221201133752](https://user-images.githubusercontent.com/17705192/204974349-91890dce-64d5-4c11-9280-522d68656939.png)

**Comment by ZhangTP1996** [comment]
The reason is that we transform `data` and `label` into `pd.DataFrame` inside `openfe.fit()` to avoid bugs due to different data types. However this is quite strange as this warning does not appear in my local machine.... You can simply surpress all warnings using 
```
import warnings
warnings.filterwarnings("ignore")
```
as a temporary solution. We will also try to figure out what happens in the future.
